### ISSUE TITLE
Send to clients in parallel `processTransform` and `processMessage`

### ISSUE THREAD

**Issue by jonasfj** [Jeffail/leaps#11]
I might be crazy here... But when we have:

``` go
    for key, c := range b.clients {
        // Skip sends for clients with matching tokens
        if key == request.Token {
            continue
        }
        select {
        case c.TransformChan <- dispatch:
        case <-time.After(clientKickPeriod):
            /* The client may have stopped listening, or is just being slow.
             * Either way, we have a strict policy here of no time wasters.
             */
            b.stats.Decr("binder.subscribed_clients", 1)
            b.stats.Incr("binder.clients_kicked", 1)

            b.log.Debugf("Kicking client (%v) for blocked transform send\n", key)

            delete(b.clients, key)
            close(c.TransformChan)
            close(c.MessageChan)
        }
    }
```

Should we do the send to each client in a go routing and then join them before returning... So that we're sending in parallel. I know we still want to kick slow clients, but if we have 10 clients and each of them have 100ms latency, we're looking at `1s` delay for the last client right?

Or is there some buffering on the outgoing websocket that I didn't notice? Which I doubt considering the timing code and implementation in `golang.org/x/net/websocket`.

**Comment by Jeffail** [comment]
The reason this has been left until now is I think the binder needs breaking down into smaller components. It has become very bloated. In this case we could have the messages dispatched in parallel but we can still potentially be blocked from sending and receiving transforms for `clientKickPeriod` every time a message is sent (obviously that's still better than blocking for `clientKickPeriod * nClients`).

Ideally the message dispatch should be separate from transforms, with some separate thread capable of buffering X messages and doing batch dispatches to websockets. It gets a little complicated when thinking about client lifetime being shared by both the binder and the message dispatcher so this probably isn't a small task.

**Comment by jonasfj** [comment]
I think you're right about some dispatching system (maybe).

But a simple `waitGroup` use would be a very good start. Perhaps combining that with a buffer on the send channel, then the WebSocketServer loop can pull out all messages, merge them and then send them at once.

In WebSocketServer this would be something like:

```go
select {
  case tform, open := <- w.binder.TransformRcvChan:
    tforms := make([]Transform, 1)
    tforms[0] = tform
    for {
      select {
        case tform2, open := <- w.binder.TransformRcvChan:
           tforms = append(tforms, tform2)
        default:
           break
      }
    }
   // Now send.... tforms
  case ...... // all the other cases
}
```

And ofcourse we would have to give the `TransformRcvChan` channel buffer space x messages, say 50 or so...  The timeout will then have to exist inside the `loopOutgoing` where stuff is actually sent.

That way binder won't have to deal with client timeouts... We just make the `loopOutgoing` close the connection, if sending takes more than x ms... Binder could be affected if it fills up the `TransformRcvChan` channel, but then `loopOutgoing` will close the websocket and empty the channel while asking binder to remove the client.

Note: there is probably something to do clientside here... As in don't send every single byte, but sleep maybe 50ms before sending something, so things can be merged clientside.

**Comment by Jeffail** [comment]
Finally got around to actually doing this https://github.com/Jeffail/leaps/commit/6be4116115c7dcafef291dc2defb97861bbe7dc1, in the end I've implemented it along with a `removeClient` method. It's not quite the big refactor I had in mind but it's cleaner than before at least.
