### ISSUE TITLE
Switching document without refreshing page

### ISSUE THREAD

**Issue by manchunw** [Jeffail/leaps#17]
I am now binding Ace Editor with Leaps. I am now creating a collaborative editing workspace similar to Google Docs. However, I cannot figure out the way how to switch document without refreshing the page. I try to call:

``` javascript
$client.close();  // the statement to end the current client
$client = new leap_client();
$client.bind_ace_editor(ace_editor);
$client.on("error", function(err) {
        console.log(JSON.stringify(err));
});

$client.on("connect", function() {
        $client.join_document(user, "", path);
});

$client.ACE_set_cursor_handler(function(user_id, session_id, lineHeight, top, left) { ... });

$client.connect(" {{ .Url }} ");
```

However, it turns out that two connections are editing the two files simultaneously. I studied the code and could not find an easy solution. Do you have any advice?

EDIT:
I try to clean event structure and initialize cursor position when I close the client.

``` javascript
leap_client.prototype.close = function() {
    if ( undefined !== this._heartbeat ) {
        clearTimeout(this._heartbeat);
    }
    if ( this._socket !== null && this._socket.readyState === 1 ) {
        this._socket.close();
        this._socket = null;
    }
    this.document_id = undefined;
    this._model = undefined;
    this._events = {}; // added
    this._cursor_position = 0; // added
};
```

Then I get the error that I suppose it has already initialized from start. Cannot figure out why.
`Uncaught TypeError: Cannot read property '_validate_transforms' of undefined`

**Comment by Jeffail** [comment]
Hey @manchunw,

You should also close and reconstruct the ACE editor after closing the leaps client. I personally do this on the leaps 'disconnect' event, which will be called after either the connection fails or you close it yourself.

Something like this should work:

 ```JavaScript
var client = null;
var ace_editor = null;

var new_editor = function() {
  if ( ace_editor != null || client != null ) {
    console.log("Naughty naughty!");
    return
  }

  ace_editor = ace.edit(element);
  client = new leap_client();
  client.bind_ace_editor(ace_editor);

  // Do all your other initialization stuff.
};

client.on("disconnect", function() {
  ace_editor.destroy();
  ace_editor = null;
  client = null;

  new_editor();
});

new_editor();

setTimeout(function() {
  client.close(); // This will clean up and trigger the "disconnect" event.
}. 5000);
```

**Comment by manchunw** [comment]
Thanks @Jeffail, your code is truly helpful.
I figure out the way but it is slightly more complicated than what I think.

After implementing your code, I still find some trouble in:
`Uncaught TypeError: Cannot read property 'send' of null`
which pops up quite often.

Turns out the `update_cursor()` function does not stop itself from `setInterval` loop. `clearInterval()` in `close()` function does not help. The only solution I can think of is to actively check the socket every time when I update the cursor. The problem is solved.
```javascript
binder._pos_interval = setInterval(function() {
  if (binder._leap_client._socket !== null) { // check whether socket is removed
    binder._leap_client.update_cursor.apply(binder._leap_client, [ ... ]);
  } else {
    clearInterval(binder._pos_interval);
  }
}, leap_client._POSITION_POLL_PERIOD);
```
Thanks for your help.

**Comment by Jeffail** [comment]
Hey @manchunw, just letting you know that the client API has changed drastically in the newer versions and that switching documents on the same websocket connection is now supported by default.
