### ISSUE TITLE
Poor fella dies during build

### ISSUE THREAD

**Issue by faddat** [Jeffail/leaps#18]
lib/store/azure_blob_store.go:99: not enough arguments in call to m.blobStorage.CreateBlockBlobFromReader

I'll use the released binary for nwo..... thanks for an awesome app!

**Comment by Jeffail** [comment]
Thanks @faddat,

Looks like the azure lib is unstable, I'll try and find a long term solution.

**Comment by Jeffail** [comment]
Hey @faddat,

Solved this for now by removing azure by default https://github.com/Jeffail/leaps/commit/97f17815599057f8243abd4fb2cd28a02ff8a37e.

**Comment by faddat** [comment]
Two more things, not worth re-opening the issue (unless you entertain the idea contained in #2)

1) Is the "poor lil fella" (the cute critter known as "leaps") a chipmunk, or other?  
2) Guessing you know of [Caddy](github.com/mholt/caddy).  Maybe you even know of [Caddy-Hugo](https://github.com/hacdias/caddy-hugo).  Introducing..... **caddy-hugo-leaps**  Get your doc on while getting your static on while getting your collaborate on. Just a thought?

**Comment by Jeffail** [comment]
Hey @faddat, it started off as a deer but it didn't seem right, so she ended up getting distorted beyond recognition into this masterpiece.

I've been keeping an eye on caddy, would be great to have leaps offered as a simple plug-in and it's probably a great idea, but it's not on my TODO list as of yet.

**Comment by joeblew99** [comment]
@faddet
Caddy Hugo leaps was what occurred to me also.

It would be very useful. After Editting session has ended you store it on the filesystem. I presume you don't want to store the transform history from leaps right ? 

Also I would add believe to the mix. This is a document indexer and searcher. Then you could search for documents

One thing I need is the ability to add strong types into the system. For example when you want to make templates. Huge does that and it's great, but inmy case I want to create custom types. These custom types are anyway that are expressed in a json document / golang structure basically.
I am guessing ( have not looked into it yet ) that leaps might need some change to allow for template tags in the handlebars format (for example)
@jeffail could you comment on how your system would intrinsically handle template variables ?

I am thinking about designing a type of data mapper that is golang based. It would however have to support doing the replacement of template variables into real values on the client without reloading the document. This is why first class support for template tags might have to be added to the core.

Then any GUI code ( day is) can listen to the tags and do whatever they want with them.
