### ISSUE TITLE
Connect to document closed READ ONLY

### ISSUE THREAD

**Issue by andyjeffries** [Jeffail/leaps#20]
So, now I've got it running properly, I'm trying to test collaboration.  The following are my steps:

1. Run leaps from within my project's folder
2. Open localhost:8001 on my local machine
3. Open 192.168.0.16:8001 on my iPad
4. Set my name as "andyjeffries" on my local machine's browser
5. Set my name as "andy iPad" on my iPad
6. In my local machine's browser, I click on a file "forgot_password_action.rb" in this case
7. My local machine opens it for editing
8. I tell the other developer (myself) by some means (maybe chat, maybe verbally) to open the same file
9. I click the same file on my iPad.
10. The iPad chat bar now says "Connection to document closed, document is now READ ONLY" in a red block.
11. The local machine's browser's chat bar says the same thing
12. Neither browser can now edit that file

So I don't know how I could collaboratively edit a file with another developer?

In Step 8 it would be great if the system listed all current users, what file they are looking at, with an icon to jump to the same file (and line their cursor is on).

**Comment by andyjeffries** [comment]
By the way, please don't get me nagging you for help wrong, I'm not trying to whinge - just that I love this idea and it has so much potential!

**Comment by Jeffail** [comment]
Hey @andyjeffries, not at all, any feedback is great. It especially helps as a nudge and a kind reminder that people are actually using the project!

It sounds like the editor is failing for some reason here, as the steps you took are perfectly valid. It might be access permissions for the file or something of that nature, is the service logging anything of interest as you try and edit the files? If not then also try opening the console on your browser and seeing if it's a problem with the web UI.

It's not quite what you're asking for but the web interface will change the URL you are on when you select a document, so to get someone else onto the same file that you're editing can be as simple as copying and sending them the current page URL.

Leaps was originally intended as a service without a front-end that could be used as part of a bigger platform, so the LAN pair programming part of it is a bit of a hacky tech demo more than anything else. My next effort on leaps is probably going to be to separate those two use cases into different binaries and do some heavy refactoring to make them each much simpler to pick up. Better session and user management on the UI will definitely be on my feature list for the stand alone pair programming service.

**Comment by andyjeffries** [comment]
The thing with access permissions is that it works for either person to edit a file, but just not if both are viewing the same file - doing that puts the file in to READ ONLY mode.

Good tip about sharing the URL, thanks.

Looking forward to the stand alone pair programming service - let me know if you want a beta tester!

**Comment by Jeffail** [comment]
Hey @andyjeffries, most of these points have been fixed in the new release, so I'm closing this issue. Thanks a lot for your feedback, your threads were a huge motivator and I'm really happy with the changes made as a result.

**Comment by andyjeffries** [comment]
I love it!  Just had a play with it with two browser and it's now REALLY easy and great!  Need to try to get it in to Homebrew now. If you don't get to it, I'll have a whack sometime in a week or two when I get a break in my work.
