### ISSUE TITLE
Expandable/collapsable tree

### ISSUE THREAD

**Issue by andyjeffries** [Jeffail/leaps#25]
My colleague was viewing the codebase he's working on and the treeview is massive and filled with lots of image assets.  So he wanted to collapse `app/assets/images/` (Rails app) but the tree isn't collapsible.

Would be great if it could be collapsed (and even better if the collapsing/expanding is shared between sessions).

**Comment by Jeffail** [comment]
Hey @andyjeffries, added this in a couple days ago if you want to try it out

https://github.com/Jeffail/leaps/commit/2a9cb027ef77bca57c8a8b59460736f0c2d1b3aa
