### ISSUE TITLE
azure blob storage as backend?

### ISSUE THREAD

**Issue by jonasfj** [Jeffail/leaps#3]
So I was looking at the store abstraction. And it's seems totally plausible to implement it with azure blob  storage, which has blob-level consistency. Unlike S3 where updates to an object in S3 is eventually consistent.
Goal of this would be to have a backend that can scale like crazy without maintenance :)

I wonder if you store any lists of documents as a document.. As any such document wouldn't be scalable. If you only have in-memory lists of open documents/binders, then azure blob storage
could be a super robust storage engine.

**Comment by Jeffail** [comment]
Hey @jonasfj,

The list of open documents is kept in-memory exclusively so it sounds like Azure might be a great candidate. I haven't worked with it before, but if there are existing Azure client libraries for Go then it should be a quick job to make it a storage option for leaps.

**Comment by jonasfj** [comment]
@Jeffail, nice, I'll start playing with it... Quick question though in the `store.Create(id string, doc Document)` interface is `id == doc.ID` and if so, why are both provided, it's tiny bit confusing.

**Comment by Jeffail** [comment]
Hey @jonasfj,

Looks like this is an odd remnant I left behind from a previous refactor of the store type. I'm about to push a quick change to simplify the API which should make it clearer.

**Comment by jonasfj** [comment]
awesome thanks... I think I got the other part working but it's a bit hard to test for now...
