### ISSUE TITLE
connection speed in intranet is slow.

### ISSUE THREAD

**Issue by kybin** [Jeffail/leaps#37]
I think it is mainly because it tries to connect to fonts.googleapis.com

**Comment by Jeffail** [comment]
Thanks @kybin, I'll label this as a bug, the fonts are unnecessary and even if they are included it shouldn't be in a way that blocks the page loading.

**Comment by Jeffail** [comment]
Hey @kybin, I've removed google fonts from the client, you can grab the latest release from https://github.com/Jeffail/leaps/releases/tag/v0.6.0
