### ISSUE TITLE
type non-english characters not works well.

### ISSUE THREAD

**Issue by kybin** [Jeffail/leaps#38]
I'm korean, so I should type korean in my code. But it does not working well.

When I type `한` it shows `U+0001한`. The U+0001 is shown as small chars inside a tiny box. 

If I type further it breaks my sentence.

Don't know why, but maybe encoding issue?

**Comment by Jeffail** [comment]
Hey @kybin, thanks for reporting. This is probably also related to https://github.com/Jeffail/leaps/issues/27. I've been looking into getting better support for large 2+ byte characters so I'll try and tackle this at the same time.

**Comment by Jeffail** [comment]
Hey @kybin, this should be fixed now as per https://github.com/Jeffail/leaps/issues/27
