### ISSUE TITLE
Make line-length guide optional.

### ISSUE THREAD

**Issue by kybin** [Jeffail/leaps#39]
I prefer turn off line-length guide. But it seems there is no option for it.

It would be great if we have it.

**Comment by Jeffail** [comment]
Hey @kybin, thanks for raising this. Sounds reasonable so I'll try and get it in next time I work on the UI.

**Comment by Jeffail** [comment]
Hey @kybin, I've basically accidentally added this for you since I've changed to CodeMirror, which doesn't have the line guide by default. Rest assured I will add an option to disable if it is ever reintroduced. :wink:
