### ISSUE TITLE
Edit offline and merge

### ISSUE THREAD

**Issue by gedw99** [Jeffail/leaps#40]
Do the operations allow merge later in time, like Google docs ?

**Comment by Jeffail** [comment]
Hey @gedw99, since leaps is mostly a self run tool rather than a hosted service I've limited the features within the UI for controlling document saves and work offline, since most cases where leaps is offline to a user will be because the host has intentionally closed the service down.

**Comment by joeblew99** [comment]
Sorry about missing this.
Will have a look to see how easy it is to add.
If you have any thoughts on it holler ;)
