### ISSUE TITLE
incomplete vendor directory

### ISSUE THREAD

**Issue by ilovezfs** [Jeffail/leaps#42]
Despite having a vendor directory, in the Homebrew formula we still have to fetch `golang.org/x/net` manually, or the build fails, as follows:

```
==> go build -o /usr/local/Cellar/leaps/0.6.1/bin/leaps github.com/jeffail/leaps/cmd/leaps
src/github.com/jeffail/leaps/vendor/github.com/amir/raidman/raidman.go:19:2: cannot find package "golang.org/x/net/proxy" in any of:
	/private/tmp/leaps-20170517-24817-1xfnewq/src/github.com/jeffail/leaps/vendor/golang.org/x/net/proxy (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/golang.org/x/net/proxy (from $GOROOT)
	/private/tmp/leaps-20170517-24817-1xfnewq/src/golang.org/x/net/proxy (from $GOPATH)
src/github.com/jeffail/leaps/lib/http/websocket.go:37:2: cannot find package "golang.org/x/net/websocket" in any of:
	/private/tmp/leaps-20170517-24817-1xfnewq/src/github.com/jeffail/leaps/vendor/golang.org/x/net/websocket (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/golang.org/x/net/websocket (from $GOROOT)
	/private/tmp/leaps-20170517-24817-1xfnewq/src/golang.org/x/net/websocket (from $GOPATH)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: go build -o /usr/local/Cellar/leaps/0.6.1/bin/leaps github.com/jeffail/leaps/cmd/leaps
```
It would be great if the vendor directory were complete, so that we can remove the one remaining `go_resource` block, which would make downstream maintenance easier. In particular, we have to look up the latest git commit of `golang.org/x/net` and update the formula with it, which interferes with automation of the updates.

Thanks!

**Comment by Jeffail** [comment]
Hey @ilovezfs, 

Done as of https://github.com/Jeffail/leaps/commit/578f42522a56b5da4bd4b932f199b212eeb38e0b. I'll tag it as v0.6.2. Thanks for updating the Homebrew formula.

**Comment by ilovezfs** [comment]
>Thanks for updating the Homebrew formula.

You're welcome!

>Done as of 578f425.

Thanks. That's a big help.

>I'll tag it as v0.6.2.

Perfect.

**Comment by ilovezfs** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/13644 for 0.6.2
