### ISSUE TITLE
go get failure

### ISSUE THREAD

**Issue by hshe233** [Jeffail/leaps#44]
$ go get github.com/jeffail/leaps/cmd/...
package golang.org/x/net/proxy: unrecognized import path "golang.org/x/net/proxy" (https fetch: Get https://golang.org/x/net/proxy?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by Jeffail** [comment]
Hey @hshe233, I tried it just now and it works fine. Are you able to connect to https://golang.org from a browser?

**Comment by hshe233** [comment]
Oh actually not.. Maybe I need to adjust my Internet Connect?.. Thank you anyway!
