### ISSUE TITLE
Current stable?

### ISSUE THREAD

**Issue by ilovezfs** [Jeffail/leaps#46]
https://github.com/Jeffail/leaps/releases shows 0.8.0 and 0.8.1

https://github.com/Jeffail/leaps/releases/latest points to 0.8.0

**Comment by while-loop** [comment]
Seems like 0.8.1 is the latest tag, but 0.8.0 is the latest release.

I'd go with 0.8.0 as it was a proper release with binaries.

**Comment by Jeffail** [comment]
Hey, 0.8.0 should be stable, but I've just tagged the latest at https://github.com/Jeffail/leaps/releases/tag/v0.8.2 and uploaded the binaries so you can get the latest features.

**Comment by ilovezfs** [comment]
Thanks, @Jeffail! Voilà https://github.com/Homebrew/homebrew-core/pull/23275
