### ISSUE TITLE
golang/dep

### ISSUE THREAD

**Issue by qknight** [Jeffail/leaps#48]
# motivation

please check: https://github.com/nixcloud/leaps-go-dep

using nix/nixos it is quite hard to package leaps and other go based softwares unless they use the new https://github.com/golang/dep utility. that is because we have https://github.com/nixcloud/dep2nix now and this makes some things easier.

that said, it best works if the upstream project also uses `dep` and with this repository i've played with dep deployment for leaps. so the question is: how do you like the idea of not using `git submodules` and using `dep` instead for dependency management? we at nixcloud are in the process of migrating our projects to dep.

if there is interest i would use the latest leaps master and create a PR. i'd like that!

# lib

the `lib` directory has a special role, as it is referenced by: `import` with  `github.com/Jeffail/leaps/lib` and it still does not have to be a 'single' package with an upstream git repository.

see also https://github.com/nixcloud/leaps-go-dep/blob/master/src/github.com/jeffail/leaps/leaps.go#L38

**Comment by Jeffail** [comment]
Hey @qknight,

Happy to move over to dep, I'm not a fan of submodules either and I'm already using dep on other projects. While I do this it also makes sense for me to change the paths within leaps to `github.com/Jeffail` from `github.com/jeffail` since this has caused issues for me in the past with other projects, would that change be difficult for you to deal with?

**Comment by Jeffail** [comment]
Got a branch to test it: https://github.com/Jeffail/leaps/pull/49, it's currently lacking the client library deps (ACE, CodeMirror and vue.js repos)

**Comment by Jeffail** [comment]
Merged

**Comment by qknight** [comment]
did not check it yet, but i assume this is amazing news, thanks so much!
